name: ticketzone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  animate_do: ^4.2.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.8.0
  go_router: ^15.1.3
  mobile_scanner: ^7.0.1
  postgres: ^3.5.6 
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#0D1D30"
  adaptive_icon_foreground: "assets/images/foreground.png"

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/images/
